name: shared_preferences
description: Flutter plugin for reading and writing simple key-value pairs.
  Wraps NSUserDefaults on iOS and SharedPreferences on Android.
repository: https://github.com/flutter/packages/tree/main/packages/shared_preferences/shared_preferences
publish_to: none
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+shared_preferences%22
version: 2.5.3

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: shared_preferences_android
      ios:
        default_package: shared_preferences_foundation
      linux:
        default_package: shared_preferences_linux
      macos:
        default_package: shared_preferences_foundation
      web:
        default_package: shared_preferences_web
      windows:
        default_package: shared_preferences_windows

dependencies:
  flutter:
    sdk: flutter
  shared_preferences_android:
    git:
      url: https://github.com/LShuXin/flutter_plugins.git
      path: shared_preferences/shared_preferences_android
  shared_preferences_foundation:
    git:
      url: https://github.com/LShuXin/flutter_plugins.git
      path: shared_preferences/shared_preferences_foundation
  shared_preferences_linux:
    git:
      url: https://github.com/LShuXin/flutter_plugins.git
      path: shared_preferences/shared_preferences_linux
  shared_preferences_platform_interface:
    git:
      url: https://github.com/LShuXin/flutter_plugins.git
      path: shared_preferences/shared_preferences_platform_interface
  shared_preferences_web:
    git:
      url: https://github.com/LShuXin/flutter_plugins.git
      path: shared_preferences/shared_preferences_web
  shared_preferences_windows:
    git:
      url: https://github.com/LShuXin/flutter_plugins.git
      path: shared_preferences/shared_preferences_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.9.0

topics:
  - persistence
  - shared-preferences
  - storage
